on: [push]

name: build and test docker image

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --target binary --tag pggb
      - name: Run a test on the DRB1-3123 dataset (wfmash)
        run: docker run -v ${PWD}/data/:/data pggb "pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 20000 -n 10 -t 16 -v -L -V 'gi|568815561:#' -o drib1 -m -C cons,10,100,1000,10000"
      - name: Run a test on the LPA dataset (wfmash)
        run: docker run -v ${PWD}/data/:/data pggb "pggb -i data/LPA/LPA.fa.gz -p 95 -s 50000 -l 10000 -G 5000,5500 -n 90 -k 79 -t 2 -v -L -Z -C 10,100,1000,10000 -O 0.001 -m"
