on: [push]

name: build and test docker image

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --target binary --tag pggb
      - name: Run a test on the DRB1-3123 dataset (wfmash)
        run: docker run -v ${PWD}/data/:/data pggb "pggb -i data/HLA/DRB1-3123.fa.gz -s 500 -l 2000 -p 75 -I 0.75 -R 0.05 -n 10 -k 9 -t 2 -v -L -Z -C 10,100,1000,10000 -O 0"
      - name: Run a test on the LPA dataset (wfmash)
        run: docker run -v ${PWD}/data/:/data pggb "pggb -i data/LPA/LPA.fa.gz -p 95 -s 500 -l 10000 -w 10000000 -G 5000 -n 1000 -k 47 -I 0.95 -R 0.05 -j 100 -e 0 -t 2 -v -L -Z -C 10,100,1000,10000 -O 0"
